### ISSUE TITLE
exa is deprecated; prefer eza instead

### ISSUE THREAD

**Issue by denisdefreyne** [mhoye/moderntools#1]
`exa` is deprecated. The [exa repository](https://github.com/ogham/exa) says:

> **exa is unmaintained, use the [fork eza](https://github.com/eza-community/eza) instead.**
> 
> (This repository isn’t archived because the only person with the rights to do so is unreachable).

eza works well.

**Comment by mhoye** [comment]
Thank you - I've made the change.
