### ISSUE TITLE
pdfpc

### ISSUE THREAD

**Issue by twsh** [mhoye/moderntools#7]
Would this be a reasonable specialised tool?

I use this whenever I have to present Beamer slides from my laptop. It handles speaker notes and timing.

https://pdfpc.github.io/

**Comment by mhoye** [comment]
I'm not sure if there's room on this list for services that have an open-source component, but I haven't thought about it much.

**Comment by mhoye** [comment]
I think I'm going to decline this; "FOSSy versions of existing tools" isn't quite what I'm after here. It's an interesting thing but I don't think this is the right place for it.
